name: tagflow_table
description: A pluggable package for tagflow to add support for advanced HTML tables.
version: 0.0.2-dev.6
repository: https://github.com/devaryakjha/tagflow
homepage: https://docs.arya.run/tagflow
issue_tracker: https://github.com/devaryakjha/tagflow/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  tagflow: ^0.0.1-dev.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  html: any

flutter:
  uses-material-design: true