name: tagflow_example
description: "An example app for the Tagflow package"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  tagflow: ^0.0.1-dev.13
  tagflow_table:
    path: ../../packages/tagflow_table
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
