name: tagflow
description: Transform HTML markup into native Flutter widgets with an elegant, customizable converter.
version: 0.0.1-dev.1
repository: https://github.com/devaryakjha/tagflow
homepage: https://docs.arya.run/tagflow
issue_tracker: https://github.com/devaryakjha/tagflow/issues

environment:
  sdk:  '^3.6.0'
  flutter: ">=3.10.0"

resolution: workspace

dependencies:
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  html: ^0.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
